# Generated by Django 2.2.14 on 2026-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', '待处理'), ('S', '已发货'), ('D', '配送中'), ('C', '已完成')], default='P', max_length=1),
        ),
    ]
