# Generated by Django 5.2.8 on 2026-01-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivering'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
